name: Deploy API to Test
on:
  workflow_dispatch:
 
jobs:
  sonarcloud:
    runs-on: ubuntu-latest
    environment: action-test
    env:
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
    steps:
      - uses: actions/setup-node@v4
        with:
          node-version: "21.2.0"

      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install dependencies
        run: npm install

      - name: Test E2E
        run: npm run test:e2e

      - name: Test and coverage
        run: npm run test:cov

      - name: SonarCloud Scan
        uses: sonarsource/sonarcloud-github-action@master
  publish:
    runs-on: ubuntu-latest
    environment: action-test
    needs: sonarcloud
    steps:
      - name: Git Checkout
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: brewery/tilda:latest-dev
          platforms: linux/amd64,linux/arm64