name: Release Workflow

on:
  release:
    types: [published]

jobs:
  publish:
    runs-on: ubuntu-latest
    environment: action-test
    steps:
      - name: Git Checkout
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Get version from release tag
        id: extract_version
        run: echo ::set-output name=version::$(echo "${{ github.event.release.tag_name }}" | cut -d 'v' -f 2)
  
      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: |
            brewery/tilda:${{ steps.extract_version.outputs.version }}
            brewery/tilda:latest
          platforms: linux/amd64,linux/arm64
